filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - “/var/log/*.log"

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.elasticsearch:
  hosts: [ "https://es01:9200" ]
  index: "filebeat-local-logs-%{[agent.version]}"
  username: "elastic"
  password: "topsecret"
  ssl.certificate_authorities: "/usr/share/filebeat/config/certs/ca/ca.crt"

setup.template.name: "filebeat-local-logs"
setup.template.pattern: "filebeat-local-logs-%{[agent.version]}"